name: First Workflow

on:
  push:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Print Message
        run: echo "Hello DevOps"
        
      - name: Show date
        run: date
    
      - name: Show Current Directory
        run: pwd
    
      - name: Show List of Files
        run: ls -la
        
        
